/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* define if the compiler has ext/hash_map */
#define HAVE_EXT_HASH_MAP 

/* Define to 1 if you have the `gb' library (-lgb). */
/* #undef HAVE_LIBGB */

/* define if the compiler implements namespaces */
#define HAVE_NAMESPACES 

/* Name of package */
#define PACKAGE "p2psim"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Version number of package */
#define VERSION "0.3"

/* Define if using the dmalloc debugging malloc package */
/* #undef WITH_DMALLOC */

/* Define if using Thomer's malloc debugging tool */
/* #undef WITH_TMGDMALLOC */
